logo: /images/avatar.png
han_type: zh-Hant
menu:
  首页: /
  归档: /pigeonhole
  链接: /links
  关于: /about
disqus:
  short_name: YOUR_DUOSHUO_ID
icon:
  rss: /atom.xml
  github: zjffun
favicon: favicon.ico
